config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/kelseyhightower/nocode:
      branch: master
      repo: https://github.com/kelseyhightower/nocode
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/kelseyhightower/nocode git:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-seashell-cuttlefish.sh
        container: qc.acc_hilly-cardinal-discus
  QC.Doc:
    repos:
      github.com/kelseyhightower/nocode find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-turquoise-goose.sh
        container: qc.doc_pretty-cerulean-nightingale
      github.com/kelseyhightower/nocode git:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-violet-barracuda.sh
        container: qc.doc_blurry-viridian-sheep
      github.com/kelseyhightower/nocode markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-gold-loon.sh
        container: qc.doc_messy-pumpkin-seahorse
  QC.Lic:
    repos:
      github.com/kelseyhightower/nocode licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-cardinal-burmese.sh
        container: qc.lic_sickly-charcoal-rottweiler
  QC.Sty:
    repos:
      github.com/kelseyhightower/nocode hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-brass-axolotl.sh
        container: qc.sty_cloudy-eggplant-impala
  QC.Ver:
    repos:
      github.com/kelseyhightower/nocode get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-beige-ladybird.sh
        container: qc.ver_blurry-bronze-mouse
timeout: 1800
